image: $CI_IMAGE

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - source /opt/ros/setup.bash

format:
  script:
    - mkdir build && cd build
    - cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ../
    - make format
    - test -z "$(git diff)" && exit 0 || exit 1

example-build:
  script:
    - colcon build
