image: $CI_IMAGE

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - source /opt/ros/setup.bash

example-build:
  script:
    - colcon build
    - colcon test
    - colcon test-result --verbose
