- type: kenning.dataproviders.ros2_segmentation_data_provider.ROS2SegmentationDataProvider
  parameters:
    topic_name: instance_segmentation_kenning
    output_memory_layout: NCHW
    output_width: 550
    output_height: 550
  outputs:
    frame: cam_frame
    frame_original: cam_frame_original
    segmentations: segmentations

- type: kenning.runners.modelruntime_runner.ModelRuntimeRunner
  parameters:
    model_wrapper:
      type: kenning.modelwrappers.pose_estimation.mmpose_onnx.MMPoseDetectionInput
      parameters:
        model_path: kenning:///models/pose_estimation/mmpose_simcc.onnx
    runtime:
      type: kenning.runtimes.onnx.ONNXRuntime
      parameters:
        save_model_path: kenning:///models/pose_estimation/mmpose_simcc.onnx
        execution_providers: [CUDAExecutionProvider]
        batch_size: -1
  inputs:
    processed_input: segmentations
  outputs:
    pose_output: predictions

- type: kenning.outputcollectors.ros2_pose_outputcollector.ROS2PoseOutputCollector
  parameters:
    topic_name: pose_estimation_kenning
    input_color_format: BGR
    input_memory_layout: NCHW
  inputs:
    frame_original: cam_frame_original
    output: predictions
