- type: kenning.dataproviders.ros2_camera_node_data_provider.ROS2CameraNodeDataProvider
  parameters:
    topic_name: camera_frame
    output_memory_layout: NCHW
    output_width: 640
    output_height: 640
  outputs:
    frame: cam_frame
    frame_original: cam_frame_original

- type: kenning.runners.modelruntime_runner.ModelRuntimeRunner
  parameters:
    model_wrapper:
      type: kenning.modelwrappers.pose_estimation.mmpose_rtmo_onnx.MMPoseRTMOONNX
      parameters:
        model_path: kenning:///models/pose_estimation/mmpose_rtmo.onnx
    runtime:
      type: kenning.runtimes.onnx.ONNXRuntime
      parameters:
        save_model_path: kenning:///models/pose_estimation/mmpose_rtmo.onnx
        execution_providers: [CUDAExecutionProvider]
        batch_size: -1
  inputs:
    processed_input: cam_frame
  outputs:
    pose_output: poses

- type: kenning.outputcollectors.ros2_pose_outputcollector.ROS2PoseOutputCollector
  parameters:
    topic_name: pose_estimation_kenning
    input_color_format: BGR
    input_memory_layout: NCHW
  inputs:
    frame_original: cam_frame_original
    output: poses
